# Generated by Django 4.2.3 on 2023-07-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tts_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mp3file',
            name='name',
            field=models.CharField(default='audio', max_length=255),
        ),
        migrations.AlterField(
            model_name='mp3file',
            name='content',
            field=models.FileField(upload_to='mp3_files/'),
        ),
    ]
